### PR TITLE
Add option to draw samples without replacement

### PR DESCRIPTION
**Pull request by wgprojects**
Original implementation sampled from the data set with replacement (allowing duplicates), which is not appropriate for many cases.

### CODE REVIEW

**Review by adamlm — CHANGES_REQUESTED** [review]
Thanks for the contribution!

The implementation looks good to me, but the linter is complaining about some trailing white space. If you resolve that, I can merge your PR.

**Comment by wgprojects** [comment]
Thanks. Is there a way I can run the linter myself to check?

Sent from Yahoo Mail on Android 
 
  On Tue., 9 Aug. 2022 at 10:23 p.m., Adam ***@***.***> wrote:   


@adamlm requested changes on this pull request.

Thanks for the contribution!

The implementation looks good to me, but the linter is complaining about some trailing white space. If you resolve that, I can merge your PR.

**Comment by adamlm** [comment]
Yes, assuming you have the `pylint` package installed. From the `pyransac` directory, run

```shell
python3 -m pylint setup.py pyransac/ tests/*.py
```

This will lint `setup.py`, the `pyransac` package, and the test files. It is the same command used in the GitHub workflow (`.github/workflows/continuous_integration.yml` if you're curious).

**Comment by adamlm** [comment]
Thanks again for the contribution!

**Pull request merged**
